Operating System 2: Let's play in the dedalus!: src/ariadneString.c File Reference
src/ariadneString.c File Reference
Ariadne string definition and management.
#include "ariadneString.h"
#include "display.h"
#include "gps.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
string string_new ()
Create a new string.
void string_delete (string *pS)
Delete a string.
bool string_remove_link (string *pS)
Remove the first item of the string (last move) if possible.
bool string_add_link (string *pS, compass_t c)
Add a move in the string.
bool string_can_go_back (const string s)
Check if the last move was a go back.
size_t string_size (const string s)
Length of the string.
Detailed Description
Ariadne string definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file ariadneString.c.
Function Documentation
bool string_add_link (string * pS, compass_t c)
Add a move in the string.
Parameters:
[in,out] pS The string to modify.
[in] c From where we come from.
Returns:
true Modification ok.
false Internal error. Operation failed.
Definition at line 48 of file ariadneString.c.
Referenced by character_play().
bool string_can_go_back (const string s)
Check if the last move was a go back.
Parameters:
[in] s The string to check.
Returns:
true It was a go back.
false It was not a go back.
Definition at line 61 of file ariadneString.c.
Referenced by character_play().
void string_delete (string * pS)
Delete a string.
Parameters:
[in,out] pS The string to delete.
Definition at line 24 of file ariadneString.c.
Referenced by character_delete().
string string_new ()
Create a new string.
Returns:
string An empty string.
Definition at line 20 of file ariadneString.c.
bool string_remove_link (string * pS)
Remove the first item of the string (last move) if possible.
Parameters:
[in,out] pS The string to modify.
Returns:
true The modification was done.
false The modification was not done (empty string).
Definition at line 36 of file ariadneString.c.
Referenced by character_play().
size_t string_size (const string s)
Length of the string.
Parameters:
[in] s The string to measure.
Returns:
size_t Number of link in the string.
Definition at line 79 of file ariadneString.c.
Referenced by _display_ui_player_body(), and string_can_go_back().