Operating System 2: Let's play in the dedalus!: src/game.c File Reference
src/game.c File Reference
Dedalus game controller.
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "display.h"
#include "game.h"
#include "gps.h"
Functions
void _game_init_moves_prop (const game_t *pGame, moves_prop_t **pMoves, size_t *pNbChar)
Initialize a moves propositions array.
void _game_get_moves_propositions (game_t *pGame, moves_prop_t *pMoves, size_t nbChar)
Get all moves propositions for each character.
void _gave_solve_moves_conflicts (const game_t *pGame, moves_prop_t *moves, size_t nbChar)
Solve conflicts between an array of move propositions.
void _game_death_caractere (game_t *pGame, character_t *pC)
Set a character as dead for this game.
void _game_exit_character (game_t *pGame, character_t *pC)
A player exits the dedalus.
bool _game_should_fight (const character_t *pC1, const character_t *pC2)
Says if two character should fight eachother.
void _game_fight (game_t *pGame, character_t *pC1, character_t *pC2)
Run and display a fight between two characters.
void _game_fight_manager_char (game_t *pGame, character_t *pC)
Check and run all fights for a given character.
void _game_fight_manager (game_t *pGame)
Check and run all fights for all characters.
pos_t _game_character_target (game_t *pGame, const character_t *pC)
Define and set the target for a given character according to the board configuration.
void _game_play_character (game_t *pGame, character_t *pC, compass_t move, bool cheated)
Play a character move.
void _game_play_characters (game_t *pGame, const moves_prop_t *moves, size_t nbChar)
Play all characters according to a set of moves.
void _game_play_refresh_ui (const game_t *pGame)
Refresh display for everybody.
ending_t _game_ending_gm (const game_t *pGame)
Compute the end game status (win or loose) for the game master.
ending_t _game_ending_player (const game_t *pGame, const character_t *pC)
Compute the end game status (win or loose) for a player.
bool game_init (game_t *pGame, config_t *pConf, const char *gameName, map_t *pMap, int pDefHealth, ai_t pAi, int mDefHealth, ai_t mAi)
Initialize a game.
void game_start (game_t *pGame)
Run an initialised game.
void game_delete (game_t *pGame)
Clear all allocated content of a game.
Detailed Description
Dedalus game controller.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-25
Copyright:
Copyright (c) 2019
Definition in file game.c.
Function Documentation
pos_t _game_character_target (game_t * pGame, const character_t * pC)
Define and set the target for a given character according to the board configuration.
Parameters:
[in,out] pGame The game to change.
[in] pC The charactere to find a target.
Returns:
pos_t The position of the target for this character.
Note:
The target is the closest opponent if any. Else it is the closest exit for a player.
Definition at line 327 of file game.c.
Referenced by _game_play_character(), and game_init().
void _game_death_caractere (game_t * pGame, character_t * pC)
Set a character as dead for this game.
Parameters:
[in,out] pGame The game to change.
[in] pC The character to define has dead.
Definition at line 220 of file game.c.
Referenced by _game_fight(), and _game_play_character().
ending_t _game_ending_gm (const game_t * pGame)
Compute the end game status (win or loose) for the game master.
Parameters:
[in] pGame The game considered.
Returns:
ending_t An ending for the GM.
Definition at line 502 of file game.c.
Referenced by game_start().
ending_t _game_ending_player (const game_t * pGame, const character_t * pC)
Compute the end game status (win or loose) for a player.
Parameters:
[in] pGame The game considered.
[in] pC The player considered.
Returns:
ending_t An ending for the player.
Returns the global ending i.e. how successful was the player team considering the player personal result.
Definition at line 509 of file game.c.
Referenced by game_start().
void _game_exit_character (game_t * pGame, character_t * pC)
A player exits the dedalus.
Parameters:
[in,out] pGame The game to change.
[in,out] pC The player that exits.
Note:
The character must be a player. Otherwise it exits with a fatal error.
Definition at line 236 of file game.c.
Referenced by _game_play_character().
void _game_fight (game_t * pGame, character_t * pC1, character_t * pC2)
Run and display a fight between two characters.
Parameters:
[in,out] pGame The game to change.
[in,out] pC1 First opponent.
[in,out] pC2 Second opponent.
Note:
This function never checks if the two characters should fight.
Definition at line 258 of file game.c.
Referenced by _game_fight_manager_char().
void _game_fight_manager (game_t * pGame)
Check and run all fights for all characters.
Parameters:
[in,out] pGame The game to change.
Definition at line 315 of file game.c.
Referenced by game_start().
void _game_fight_manager_char (game_t * pGame, character_t * pC)
Check and run all fights for a given character.
Parameters:
[in,out] pGame The game to change.
[in,out] pC The concerned character.
Definition at line 292 of file game.c.
Referenced by _game_fight_manager().
void _game_get_moves_propositions (game_t * pGame, moves_prop_t * pMoves, size_t nbChar)
Get all moves propositions for each character.
Parameters:
[in] pGame The game considered.
[in,out] pMoves An initialized vector of propositions.
[in] nbChar Number of character considered.
Note:
The array pMoves must be initialized before the call.
Definition at line 349 of file game.c.
Referenced by game_start().
void _game_init_moves_prop (const game_t * pGame, moves_prop_t ** pMoves, size_t * pNbChar)
Initialize a moves propositions array.
Parameters:
[in] pGame The game considered.
[out] pMoves Allocated array of moves propositions for each character.
[out] pNbChar Size of the array.
Warning:
The returned array must be free.
Definition at line 195 of file game.c.
Referenced by game_start().
void _game_play_character (game_t * pGame, character_t * pC, compass_t move, bool cheated)
Play a character move.
Parameters:
[in,out] pGame The game to change.
[in,out] pC The character to play.
[in] move The move to play.
[in] cheated The AI tries to cheat when move proposition was asked.
[in] cheated Says if the AI tries to cheat.
Definition at line 431 of file game.c.
Referenced by _game_play_characters().
void _game_play_characters (game_t * pGame, const moves_prop_t * moves, size_t nbChar)
Play all characters according to a set of moves.
Parameters:
[in,out] pGame The game to change.
[in] moves Array of moves to play.
[in] nbChar Number of characters considered.
Definition at line 477 of file game.c.
Referenced by game_start().
void _game_play_refresh_ui (const game_t * pGame)
Refresh display for everybody.
Parameters:
[in] pGame The game to display.
Definition at line 486 of file game.c.
Referenced by _game_fight(), and game_start().
bool _game_should_fight (const character_t * pC1, const character_t * pC2)
Says if two character should fight eachother.
Parameters:
[in] pC1 A character.
[in] pC2 A character.
Returns:
true A fight should take place.
false No fight possible.
Note:
A fight is possible if the characters are not dead, not of the same type (one player vs one minotaur) and if they are at the same or an adjacent position.
Definition at line 248 of file game.c.
Referenced by _game_fight_manager_char().
void _gave_solve_moves_conflicts (const game_t * pGame, moves_prop_t * moves, size_t nbChar)
Solve conflicts between an array of move propositions.
Parameters:
[in] pGame The game considered.
[in,out] moves The array of moves propositions to clear.
[in] nbChar Number of character considered.
The "moves" arrays will be cleaned to remove conflicts. A conflict occurs when two characters want to go at the same position. In this version only one character will move (players firsts and in order of declaration after).
Definition at line 359 of file game.c.
Referenced by game_start().
void game_delete (game_t * pGame)
Clear all allocated content of a game.
Parameters:
[in,out] pGame The game to clear.
Definition at line 700 of file game.c.
Referenced by main().
bool game_init (game_t * pGame, config_t * pConf, const char * gameName, map_t * pMap, int pDefHealth, ai_t pAi, int mDefHealth, ai_t mAi)
Initialize a game.
Parameters:
[out] pGame The game to initialise.
[in,out] pConf Configuration structure for the game.
[in] gameName Name for the game.
[in,out] pMap Initial map of the game.
[in] pDefHealth Default health for players.
[in] pAi Default AI for players.
[in] mDefHealth Default health for minotaurs.
[in] mAi Default AI for minotaurs.
Returns:
true If the game is correctly initialised.
false If there is some mistakes (no exit, no player ...).
Definition at line 532 of file game.c.
Referenced by main().
void game_start (game_t * pGame)
Run an initialised game.
Parameters:
[in,out] pGame The game to start.
Definition at line 643 of file game.c.
Referenced by main().