Operating System 2: Let's play in the dedalus!: src/map.h File Reference
src/map.h File Reference
Map definition and management.
#include <stdbool.h>
#include <stdlib.h>
Data Structures
struct pos_t
coordinate in a map.
struct map_t
A map of the dedalus (one level).
Enumerations
enum map_content_t {
END_ROW = '\0', PLAYER = '@', EXIT = '?', WALL = '*',
PATH = '.', MINOTAUR = '&', DEAD = '+', DISPLAY_MASK = 'X'
}
List of symbols that can occur in a map or in a mask map.
Functions
bool map_reader (const char *filename, map_t *pMap, size_t mapMaxXSize)
Read a map from a file.
void map_delete (map_t *pMap)
Clear the content of the map.
map_t * map_mask_init (const map_t *pMap)
Build an empty display mask from a map.
void map_mask_add (map_t *pMask, pos_t p)
Add a position to display in a map mask.
Detailed Description
Map definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-24
Copyright:
Copyright (c) 2019
Definition in file map.h.
Data Structure Documentation
struct pos_t
coordinate in a map.
Definition at line 21 of file map.h.
Data Fields
size_t x column coordinate.
size_t y row coordinate.
struct map_t
A map of the dedalus (one level).
Note:
The matrix contains char instead of map_content_t in order to be wild enough to store all kind of characters.
Definition at line 47 of file map.h.
Data Fields
char ** m Matrix of caracters.
size_t x Number of columns.
size_t y Number of rows.
Enumeration Type Documentation
enum map_content_t
List of symbols that can occur in a map or in a mask map.
Enumerator:
END_ROW
Symbol for the end of a row.
PLAYER
Symbol for a player.
EXIT
Symbol for an exit.
WALL
Symbol for a wall.
PATH
Symbol for an empty path in the dedalus.
MINOTAUR
Symbol for a minotaur.
DEAD
Symbol for a dead character.
DISPLAY_MASK
Symbol in a mask map to ask for a display.
Definition at line 30 of file map.h.
Function Documentation
void map_delete (map_t * pMap)
Clear the content of the map.
Parameters:
[in,out] pMap Pointer to the map to clear.
Note:
The map itself is not free, only its content.
Definition at line 60 of file map.c.
Referenced by character_delete(), game_delete(), main(), and map_reader().
void map_mask_add (map_t * pMask, pos_t p)
Add a position to display in a map mask.
Parameters:
[in,out] pMask
[in] p Position to add in the mask (i.e. to display).
Note:
Add the given position and the neighborhood.
Definition at line 151 of file map.c.
Referenced by _character_make_move(), and game_init().
map_t* map_mask_init (const map_t * pMap)
Build an empty display mask from a map.
Parameters:
[in] pMap The map associated to the mask to create.
Returns:
map_t* An empty map mask (displays nothing).
Definition at line 138 of file map.c.
Referenced by game_init().
bool map_reader (const char * filename, map_t * pMap, size_t mapMaxXSize)
Read a map from a file.
Parameters:
[in] filename Path to the file that contains the map in a text format.
[out] pMap The loaded map if loading succeed, *NULL else).
[in] mapMaxXSize Maximum width of a board.
Returns:
true Loading succeed.
false Loading failed (wrong format or missing content)
Definition at line 75 of file map.c.
Referenced by main().