Operating System 2: Let's play in the dedalus!: src/character.c File Reference
src/character.c File Reference
Character definition and management.
#include <limits.h>
#include <unistd.h>
#include "ariadneString.h"
#include "character.h"
#include "display.h"
#include "gps.h"
Functions
bool _character_can_go (map_t map, pos_t pos, compass_t c)
Is it possible to go in a given direction?
bool _character_is_valid_move (compass_t c, bool n, bool e, bool s, bool w)
Is a move provided by an AI valid, considering the valid directions?
void _character_make_move (map_t *pMap, character_t *pC, compass_t c, bool *pExited)
Move a character.
pid_t _character_get_child_pid (pid_t pid)
Get the pid of the child of a given pid.
character_t character_init (map_content_t type, pid_t id, bool dispInChild, const char *name, int health, ai_t ai)
Initialize a character.
compass_t character_propose_move (const character_t *pC, const map_t *pMap, bool *pCheated)
Ask a character the move she wants to play.
void character_play (character_t *pC, compass_t move, pos_t targetPos, map_t *pMap, int steps, int maxMoves, bool *pExited)
Play a move for a character.
void character_is_dead (map_t *pMap, character_t *pC)
Set a character as dead.
void character_is_out (map_t *pMap, character_t *pC)
A Charater exit the maze.
void character_delete (map_t *pMap, character_t *pC)
Clear a character structure.
Detailed Description
Character definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file character.c.
Function Documentation
bool _character_can_go (map_t map, pos_t pos, compass_t c)
Is it possible to go in a given direction?
Parameters:
[in] map The considered map.
[in] pos The stating position.
[in] c The considered direction.
Returns:
true Yes you can.
false No you can not.
Definition at line 73 of file character.c.
Referenced by character_propose_move().
pid_t _character_get_child_pid (pid_t pid)
Get the pid of the child of a given pid.
Parameters:
[in] pid The parent pid.
Returns:
pid_t The child pid.
Note:
Usefull if you only have the pid of a Xterm and you want the pid of the bash.
Definition at line 141 of file character.c.
Referenced by character_init().
bool _character_is_valid_move (compass_t c, bool n, bool e, bool s, bool w)
Is a move provided by an AI valid, considering the valid directions?
Parameters:
[in] c The selected direction.
[in] n Is it possible to go north?
[in] e Is it possible to go east?
[in] s Is it possible to go south?
[in] w Is it possible to go west?
Returns:
true It is valide move.
false The AI try to cheat.
Definition at line 106 of file character.c.
Referenced by character_propose_move().
void _character_make_move (map_t * pMap, character_t * pC, compass_t c, bool * pExited)
Move a character.
Parameters:
[in,out] pMap The considered map.
[in,out] pC The considered character.
[in] c The wanted direction for the move.
[out] pExited Does the character reach an exit?
Definition at line 111 of file character.c.
Referenced by character_play().
void character_delete (map_t * pMap, character_t * pC)
Clear a character structure.
Parameters:
[in,out] pMap The map.
[in,out] pC The character to clear.
Definition at line 328 of file character.c.
Referenced by game_delete().
character_t character_init (map_content_t type, pid_t id, bool dispInChild, const char * name, int health, ai_t ai)
Initialize a character.
Parameters:
[in] type Type of character (player, Minotaur, ...).
[in] id The id of the character.
[in] dispInChild Display in the child of the PID process id.
[in] name Name of the character.
[in] health Initial health of the character.
[in] ai AI of the character.
Returns:
character_t An initialized character (ready to play).
Definition at line 208 of file character.c.
Referenced by game_init().
void character_is_dead (map_t * pMap, character_t * pC)
Set a character as dead.
Parameters:
[in,out] pMap The map.
[in,out] pC The dying character.
He will not move and change its type.
Definition at line 315 of file character.c.
Referenced by _game_death_caractere().
void character_is_out (map_t * pMap, character_t * pC)
A Charater exit the maze.
Parameters:
[in,out] pMap The map.
[in,out] pC The character that exit.
He will not move and his position will change.
Definition at line 322 of file character.c.
Referenced by _game_exit_character().
void character_play (character_t * pC, compass_t move, pos_t targetPos, map_t * pMap, int steps, int maxMoves, bool * pExited)
Play a move for a character.
Parameters:
[in,out] pC The considered character.
[in] move The desired move.
[in] targetPos Position of the character target.
[in,out] pMap The map.
[in] steps Number of steps from the begining.
[in] maxMoves Maximum number of steps before death.
[out] pExited Says if the charactere is on an exit after the move.
Definition at line 281 of file character.c.
Referenced by _game_play_character().
compass_t character_propose_move (const character_t * pC, const map_t * pMap, bool * pCheated)
Ask a character the move she wants to play.
Parameters:
[in] pC The considered character.
[in] pMap The map.
[out] pCheated Says if the AI tries to cheat?
Returns:
compass_t The desired move.
Definition at line 266 of file character.c.
Referenced by _game_get_moves_propositions().