Operating System 2: Let's play in the dedalus!: src/config.h File Reference
src/config.h File Reference
Structure to configure the game.
#include <stdbool.h>
#include <sys/types.h>
Data Structures
struct config_t
Game configuration structure.
Functions
config_t config_init ()
Return an initialized configuration with default values.
void config_delete (config_t *pConfig)
Clear a configuration.
void config_add_display (config_t *pConfig, pid_t displayPid)
Add a display in the configuration.
Variables
const bool COLOR
Game in vintage colors if true and in B&W otherwise.
const bool DEBUG
Game in debug mode if true and in normal mode otherwise.
Detailed Description
Structure to configure the game.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-27
Copyright:
Copyright (c) 2019
Definition in file config.h.
Data Structure Documentation
struct config_t
Game configuration structure.
Definition at line 27 of file config.h.
Data Fields
bool color Display with color?
bool debug Display in debug mode (no cleaning)?
int delay Time (in us) between frames.
pid_t * displayPidA Array of pid of terminals to display players.
bool gameInfo Display more game informations?
bool interactive Ask for interactive actions from GM.
const char * mapFile Path to the map file.
size_t mapMaxXSize Max width of a map.
int maxMoves Maximum number of moves for players.
size_t nbDisplay Number of display for players.
Function Documentation
void config_add_display (config_t * pConfig, pid_t displayPid)
Add a display in the configuration.
Parameters:
[in,out] pConfig The configuration to change.
[in] displayPid The pid of the process to write into (basically a bash).
Definition at line 48 of file config.c.
Referenced by read_parameters().
void config_delete (config_t * pConfig)
Clear a configuration.
Parameters:
[in,out] pConfig The configuration to clear.
Definition at line 42 of file config.c.
Referenced by main().
config_t config_init ()
Return an initialized configuration with default values.
Returns:
config_t A default configuration.
Definition at line 22 of file config.c.
Referenced by main().