Operating System 2: Let's play in the dedalus!: src/ai/ai_random.h File Reference
src/ai/ai_random.h File Reference
Random Artificial Intelligence.
#include "../ai.h"
Functions
const char * ai_random_get_name ()
Get the name of the random AI class.
ai_t ai_random_new ()
Create a new AI that will move randomly.
Detailed Description
Random Artificial Intelligence.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file ai_random.h.
Function Documentation
const char* ai_random_get_name ()
Get the name of the random AI class.
Returns:
const char* The name of the AI.
Definition at line 82 of file ai_random.c.
Referenced by ai_new(), ai_random_new(), and main().
ai_t ai_random_new ()
Create a new AI that will move randomly.
Returns:
ai_t The new AI.
Definition at line 86 of file ai_random.c.
Referenced by ai_new().