Operating System 2: Let's play in the dedalus!: src/ai/ai_shall_not_pass.h File Reference
src/ai/ai_shall_not_pass.h File Reference
Artificial Intelligence who will not move.
#include "../ai.h"
Functions
const char * ai_shall_not_pass_get_name ()
Get the name of the "shall not pass" AI class.
ai_t ai_shall_not_pass_new ()
Create a new AI that will never move.
Detailed Description
Artificial Intelligence who will not move.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file ai_shall_not_pass.h.
Function Documentation
const char* ai_shall_not_pass_get_name ()
Get the name of the "shall not pass" AI class.
Returns:
const char* The name of the AI.
Definition at line 46 of file ai_shall_not_pass.c.
Referenced by ai_new(), and ai_shall_not_pass_new().
ai_t ai_shall_not_pass_new ()
Create a new AI that will never move.
Returns:
ai_t The new AI.
Definition at line 50 of file ai_shall_not_pass.c.
Referenced by ai_new().