Operating System 2: Let's play in the dedalus!: src/display.c File Reference
src/display.c File Reference
Methods to display a dedalus.
#include <string.h>
#include <termios.h>
#include <unistd.h>
#include "ariadneString.h"
#include "display.h"
#include "gps.h"
Defines
#define ANSI_COLOR_RED "\x1b[31m"
Start red color.
#define ANSI_COLOR_GREEN "\x1b[32m"
Start green color.
#define ANSI_COLOR_YELLOW "\x1b[33m"
Start yellow color.
#define ANSI_COLOR_BLUE "\x1b[34m"
Start blue color.
#define ANSI_COLOR_MAGENTA "\x1b[35m"
Start magenta color.
#define ANSI_COLOR_CYAN "\x1b[36m"
Start cyan color.
#define ANSI_COLOR_WHITE "\x1b[37m"
Start white color.
#define ANSI_COLOR_RESET "\x1b[0m"
back to default color
#define PLAYER_COLOR ANSI_COLOR_RED
Default color for players.
#define EXIT_COLOR ANSI_COLOR_GREEN
Default color for exits.
#define WALL_COLOR ANSI_COLOR_BLUE
Default color for walls.
#define PATH_COLOR ANSI_COLOR_YELLOW
Default color for paths.
#define MINOTAUR_COLOR ANSI_COLOR_MAGENTA
Default color for Minotaurs.
#define DEFAULT_COLOR ANSI_COLOR_RESET
Default color.
Functions
void _display_move_up (FILE *stream, size_t nbRow)
Move cursor up to clear something for example.
void _display_ring_bell (FILE *stream)
Ring the bell of a terminal.
void _display_clear_map (FILE *stream, const map_t *pMap)
Remove the map in a stream.
const char * _display_wall_to_string (const map_t *pMap, const map_t *pMask, const pos_t p)
Get the string associated to a wall.
const char * _display_path_to_string ()
Get the string for a path in the dedalus.
const char * _display_player_to_string ()
Get the string for a player in the dedalus.
const char * _display_dead_to_string ()
Get the string for a dead character in the dedalus.
const char * _display_exit_to_string ()
Get the string for an exit in the dedalus.
const char * _display_minotaur_to_string ()
Get the string for a Minotaur in the dedalus.
void _display_map (FILE *stream, const map_t *pMap, const map_t *pMask)
Display a map.
void _display_string (FILE *stream, const string s)
Display the ariadne string.
void _display_gameover (FILE *stream)
Display a "Gameover" message.
void _display_try_again (FILE *stream)
Display a "try again" message.
void _display_congratulations (FILE *stream)
Display a "Congratulation" message.
void _display_credits (FILE *stream)
Display credits for the dedalus game.
void _display_health (FILE *stream, double health)
Display health of a character.
void _display_ui_gm_header (FILE *stream, const char *level, const map_t *pMap, int delay, bool gameInfo)
Display the GM UI header.
void _display_ui_gm_body (FILE *stream, const map_t *pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, bool refresh)
Display the GM UI body (the map).
void _display_ui_player_header (FILE *stream, const char *level, const char *ai, const map_t *pMap, const character_t *pPlayer, int delay, int maxMoves, bool gameInfo)
Display a player UI header.
void _display_ui_player_body (FILE *stream, const map_t *pMap, const character_t *pPlayer, bool refresh)
Display a player ui body (the map).
void _display_player_ending (FILE *stream, ending_char_t ending)
Display a ending message for a player.
void _display_fight (FILE *stream, char endingScene[], size_t sceneLength, double health, const char *opponent, bool lastDisplay)
Display a fight scene.
void _display_fight_introduction (char *scene, size_t sceneLength, const character_t *pC1, const character_t *pC2, size_t delay)
Display a fight introduction animation.
void _display_fight_ending (const character_t *pWinner, const character_t *pLooser, bool tied)
Display the final message after a fight. Depending of who win.
void display_ui_gm (FILE *stream, const char *level, const map_t *pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, int delay, bool gameInfo, bool refresh)
Display the game master interface.
void display_ui_player (const char *level, const char *ia, const map_t *pMap, const character_t *pPlayer, int delay, int maxMoves, bool gameInfo, bool header, bool refresh)
Display a player interface.
void display_ending (FILE *stream, ending_t ending)
Display an ending message.
void display_fight_iteration (const map_t *pMap, const character_t *pC1, const character_t *pC2, size_t delay, size_t iteration)
Display on iteration of a fight.
void display_fight_clear (FILE *stream)
Clear the display of a finished fight.
void display_fatal_error (FILE *stream, const char *msg)
Display a fatal error.
void display_info (FILE *stream, const char *msg)
Display an information message.
void display_wait_user (FILE *stream, const char *preMsg, bool waitUser)
Wait a user interaction.
Detailed Description
Methods to display a dedalus.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-24
Copyright:
Copyright (c) 2019
Definition in file display.c.
Function Documentation
void _display_clear_map (FILE * stream, const map_t * pMap)
Remove the map in a stream.
Parameters:
[in,out] stream Where it should be printed.
[in] pMap Map to clear.
Definition at line 299 of file display.c.
Referenced by display_fight_iteration().
void _display_congratulations (FILE * stream)
Display a "Congratulation" message.
Parameters:
[in,out] stream Where it should be printed.
Definition at line 487 of file display.c.
Referenced by display_ending().
void _display_credits (FILE * stream)
Display credits for the dedalus game.
Parameters:
[in,out] stream Where it should be printed.
Definition at line 527 of file display.c.
Referenced by _display_ui_gm_header(), and _display_ui_player_header().
const char * _display_dead_to_string ()
Get the string for a dead character in the dedalus.
Returns:
const char* The string for a dead character.
Definition at line 380 of file display.c.
Referenced by _display_fight(), and _display_map().
const char * _display_exit_to_string ()
Get the string for an exit in the dedalus.
Returns:
const char* The string for an exit.
Definition at line 387 of file display.c.
Referenced by _display_fight(), and _display_map().
void _display_fight (FILE * stream, char endingScene[], size_t sceneLength, double health, const char * opponent, bool lastDisplay)
Display a fight scene.
Parameters:
[in,out] stream Where it should be printed.
[in] endingScene Array of the scene.
[in] sceneLength Size of the scene.
[in] health Health of the considered character.
[in] opponent Name of the opponent.
[in] lastDisplay Is it the last display?
Definition at line 734 of file display.c.
Referenced by _display_fight_introduction(), and display_fight_iteration().
void _display_fight_ending (const character_t * pWinner, const character_t * pLooser, bool tied)
Display the final message after a fight. Depending of who win.
Parameters:
[in] pWinner The winner character.
[in] pLooser The looser character.
[in] tied Is it a tied (double KO).
Definition at line 807 of file display.c.
Referenced by display_fight_iteration().
void _display_fight_introduction (char * scene, size_t sceneLength, const character_t * pC1, const character_t * pC2, size_t delay)
Display a fight introduction animation.
Parameters:
[in,out] scene Array of the scene.
[in] sceneLength Size of the scene.
[in] pC1 First player in the fight.
[in] pC2 Second player in the fight.
[in] delay Delay (in us) between tow frames.
Definition at line 786 of file display.c.
Referenced by display_fight_iteration().
void _display_gameover (FILE * stream)
Display a "Gameover" message.
Parameters:
[in,out] stream Where it should be printed.
Definition at line 455 of file display.c.
Referenced by display_ending().
void _display_health (FILE * stream, double health)
Display health of a character.
Parameters:
[in,out] stream Where it should be printed.
[in] health health to print.
Definition at line 549 of file display.c.
Referenced by _display_fight(), and _display_ui_player_body().
void _display_map (FILE * stream, const map_t * pMap, const map_t * pMask)
Display a map.
Parameters:
[in,out] stream Where it should be printed.
[in] pMap The map to print.
[in] pMask A mask to define what position should be print. NULL to print everything.
Note:
If a mask is provided, positions in the neighborhood of marked positions are displayed.
Definition at line 397 of file display.c.
Referenced by _display_ui_gm_body(), and _display_ui_player_body().
const char * _display_minotaur_to_string ()
Get the string for a Minotaur in the dedalus.
Returns:
const char* The string for a Minotaur.
Definition at line 392 of file display.c.
Referenced by _display_fight(), and _display_map().
void _display_move_up (FILE * stream, size_t nbRow)
Move cursor up to clear something for example.
Parameters:
[in,out] stream The considered stream.
[in] nbRow Number of lines up.
Definition at line 291 of file display.c.
Referenced by _display_clear_map(), _display_fight(), _display_ui_gm_body(), _display_ui_player_body(), display_fight_clear(), and display_wait_user().
const char * _display_path_to_string ()
Get the string for a path in the dedalus.
Returns:
const char* The string for a path.
Definition at line 367 of file display.c.
Referenced by _display_fight(), and _display_map().
void _display_player_ending (FILE * stream, ending_char_t ending)
Display a ending message for a player.
Parameters:
[in,out] stream Where it should be printed.
[in] ending The ending category.
Definition at line 692 of file display.c.
Referenced by _display_ui_player_body().
const char * _display_player_to_string ()
Get the string for a player in the dedalus.
Returns:
const char* The string for a player.
Definition at line 373 of file display.c.
Referenced by _display_fight(), _display_map(), and _display_string().
void _display_ring_bell (FILE * stream)
Ring the bell of a terminal.
Parameters:
[in,out] stream The considered stream.
Definition at line 295 of file display.c.
Referenced by _display_fight(), and _display_player_ending().
void _display_string (FILE * stream, const string s)
Display the ariadne string.
Parameters:
[in,out] stream Where it should be printed.
[in] s The ariadne string to display.
Definition at line 446 of file display.c.
Referenced by _display_ui_player_body().
void _display_try_again (FILE * stream)
Display a "try again" message.
Parameters:
[in,out] stream Where it should be printed.
Definition at line 471 of file display.c.
Referenced by display_ending().
void _display_ui_gm_body (FILE * stream, const map_t * pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, bool refresh)
Display the GM UI body (the map).
Parameters:
[in,out] stream Where it should be printed.
[in] pMap The map to display.
[in] nbPlayerAlive Number of players alive.
[in] nbPlayerOnBoard Number of player still on the board.
[in] nbMinotaurAlive Number of Minotaurs alive.
[in] refresh Should clear a previously printed body.
Definition at line 617 of file display.c.
Referenced by display_ui_gm().
void _display_ui_gm_header (FILE * stream, const char * level, const map_t * pMap, int delay, bool gameInfo)
Display the GM UI header.
*
Parameters:
[in,out] stream Where it should be printed.
[in] level Level name.
[in] pMap The map (to display some information about).
[in] delay Delay between two frames (for information only).
[in] gameInfo Display more precise game informations.
Definition at line 586 of file display.c.
Referenced by display_ui_gm().
void _display_ui_player_body (FILE * stream, const map_t * pMap, const character_t * pPlayer, bool refresh)
Display a player ui body (the map).
Parameters:
[in,out] stream Where it should be printed.
[in] pMap Map to print.
[in] pPlayer Player considered.
[in] refresh If the body of the ui should be refresh.
Definition at line 671 of file display.c.
Referenced by display_ui_player().
void _display_ui_player_header (FILE * stream, const char * level, const char * ai, const map_t * pMap, const character_t * pPlayer, int delay, int maxMoves, bool gameInfo)
Display a player UI header.
Parameters:
[in,out] stream Where it should be printed.
[in] level Level name.
[in] ai AI name.
[in] pMap The map (to display some information about).
[in] pPlayer Player considered.
[in] delay Delay between two frames (for information only).
[in] maxMoves Max number of moved allowed.
[in] gameInfo Display more precise game informations.
Definition at line 635 of file display.c.
Referenced by display_ui_player().
const char * _display_wall_to_string (const map_t * pMap, const map_t * pMask, const pos_t p)
Get the string associated to a wall.
Parameters:
[in] pMap The map to consider.
[in] p The position of the wall to consider.
[in] pMask A mask to define what position should be print. NULL to print everything.
Returns:
const char* The string for the wall.
Definition at line 319 of file display.c.
Referenced by _display_map().
void display_ending (FILE * stream, ending_t ending)
Display an ending message.
Parameters:
[in,out] stream Where it should be printed.
[in] ending The ending type to display.
Definition at line 870 of file display.c.
Referenced by game_start().
void display_fatal_error (FILE * stream, const char * msg)
Display a fatal error.
Parameters:
[in,out] stream Where the message should be printed.
[in] msg Message to print.
Note:
For debug only.
Definition at line 1003 of file display.c.
Referenced by _character_get_child_pid(), _game_death_caractere(), _game_exit_character(), _game_init_moves_prop(), _gave_solve_moves_conflicts(), character_init(), gps_closest(), and main().
void display_fight_clear (FILE * stream)
Clear the display of a finished fight.
Parameters:
[in,out] stream The stream to clean
Definition at line 991 of file display.c.
Referenced by _game_fight().
void display_fight_iteration (const map_t * pMap, const character_t * pC1, const character_t * pC2, size_t delay, size_t iteration)
Display on iteration of a fight.
Parameters:
[in] pMap The map to clear for the first iteration.
[in] pC1 First character for the fight.
[in] pC2 Second character for the fight.
[in] delay Delay between two frame of the introduction step.
[in] iteration Step of the fight.
Note:
The iteration is used of the animation. Basically it is a counter that should be incremented by one between each frame.
Definition at line 926 of file display.c.
Referenced by _game_fight().
void display_info (FILE * stream, const char * msg)
Display an information message.
Parameters:
[in,out] stream Where the message should be printed.
[in] msg The message to display.
Definition at line 1034 of file display.c.
Referenced by display_wait_user().
void display_ui_gm (FILE * stream, const char * level, const map_t * pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, int delay, bool gameInfo, bool refresh)
Display the game master interface.
Parameters:
[in,out] stream Where it should be printed.
[in] level Name of the level.
[in] pMap Map to print.
[in] nbPlayerAlive Number of player still alive.
[in] nbPlayerOnBoard Number of player on board.
[in] nbMinotaurAlive Number of Minotaurs still alive.
[in] delay Delay between two frames (for information only).
[in] gameInfo Display more precise game informations.
[in] refresh If only the body of the ui should be refresh.
Definition at line 838 of file display.c.
Referenced by _game_play_refresh_ui(), and game_start().
void display_ui_player (const char * level, const char * ia, const map_t * pMap, const character_t * pPlayer, int delay, int maxMoves, bool gameInfo, bool header, bool refresh)
Display a player interface.
Parameters:
[in] level Level name.
[in] ia IA name.
[in] pMap Map to print.
[in] pPlayer Player considered for the point of view.
[in] delay Delay between two frames (for information only).
[in] maxMoves Max number of moved allowed.
[in] gameInfo Display more precise game informations.
[in] header If the header of the ui should be printed.
[in] refresh If the body of the ui should be refresh.
Note:
The output stream is defined inside the player.
Definition at line 854 of file display.c.
Referenced by _game_fight(), _game_play_refresh_ui(), and game_start().
void display_wait_user (FILE * stream, const char * preMsg, bool waitUser)
Wait a user interaction.
Parameters:
[in,out] stream The stream from where the interaction should happen.
[in] preMsg A one line message that could be printed to ask for interaction. It is removed after the interaction. NULL to display nothin.
[in] waitUser If this call really wait an interaction or just one second.
Definition at line 1044 of file display.c.
Referenced by _game_fight(), and main().