Operating System 2: Let's play in the dedalus!: src/game.h File Reference
src/game.h File Reference
Dedalus game controller.
#include "character.h"
#include "config.h"
#include "map.h"
Data Structures
struct game_t
Structure of a game.
Defines
#define DISPLAY stdout
Default display stream for the Game Master.
Functions
bool game_init (game_t *pGame, config_t *pConf, const char *gameName, map_t *pMap, int pDefHealth, ai_t pAi, int mDefHealth, ai_t mAi)
Initialize a game.
void game_start (game_t *pGame)
Run an initialised game.
void game_delete (game_t *pGame)
Clear all allocated content of a game.
Detailed Description
Dedalus game controller.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-25
Copyright:
Copyright (c) 2019
Definition in file game.h.
Data Structure Documentation
struct game_t
Structure of a game.
Definition at line 28 of file game.h.
Data Fields
int delay Delay (in us) between tow steps.
pos_t * exitA Array of exits positions.
bool finalLevel Is this level a final level (contains minotaurs).
bool gameInfo Display more precise game informations.
const char * gameName The name of the level (i.e. the map name).
bool interactive Ask for interactive actions from GM.
int maxMoves Maximum number of moves per player.
character_t * minotaurA Array of minotaurs.
size_t nbExit Number of exits.
size_t nbMinotaur Number of minotaurs.
size_t nbMinotaurAlive Number of minotaurs still alive.
size_t nbPlayer Number of players.
size_t nbPlayerAlive Number of players still alive.
size_t nbPlayerOnBoard Number of players on board (not dead and not out).
character_t * playerA Array of players.
map_t * pMap The map.
int steps Number of steps since the beginning of the game.
Function Documentation
void game_delete (game_t * pGame)
Clear all allocated content of a game.
Parameters:
[in,out] pGame The game to clear.
Definition at line 700 of file game.c.
Referenced by main().
bool game_init (game_t * pGame, config_t * pConf, const char * gameName, map_t * pMap, int pDefHealth, ai_t pAi, int mDefHealth, ai_t mAi)
Initialize a game.
Parameters:
[out] pGame The game to initialise.
[in,out] pConf Configuration structure for the game.
[in] gameName Name for the game.
[in,out] pMap Initial map of the game.
[in] pDefHealth Default health for players.
[in] pAi Default AI for players.
[in] mDefHealth Default health for minotaurs.
[in] mAi Default AI for minotaurs.
Returns:
true If the game is correctly initialised.
false If there is some mistakes (no exit, no player ...).
Definition at line 532 of file game.c.
Referenced by main().
void game_start (game_t * pGame)
Run an initialised game.
Parameters:
[in,out] pGame The game to start.
Definition at line 643 of file game.c.
Referenced by main().