Operating System 2: Let's play in the dedalus!: src/gps.h File Reference
src/gps.h File Reference
Orientation (GPS) definition and management.
#include "map.h"
Enumerations
enum compass_t {
North = 0, NorthEast = 1, East = 2, SouthEast = 3,
South = 4, SouthWest = 5, West = 6, NorthWest = 7,
Stay = 8
}
Enumeration of the different directions that the compass can indicate.
Functions
size_t gps_locator (const map_t *pMap, map_content_t object, pos_t **pAPos)
Returns the number of objects of a given type in a map and their position.
void gps_direction (pos_t source, pos_t target, compass_t *pC, float *pD)
Return the direction and the distance between tow positions.
pos_t gps_closest (pos_t source, const void *targets, size_t nbTargets, map_content_t arrayType)
From a position, return the direction of the closest object in an array.
const char * gps_compass_to_string (compass_t c)
Convert a compass into a string for display.
pos_t gps_compute_move (pos_t pos, compass_t move)
Compute the new positions after a move.
Detailed Description
Orientation (GPS) definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-24
Copyright:
Copyright (c) 2019
Definition in file gps.h.
Enumeration Type Documentation
enum compass_t
Enumeration of the different directions that the compass can indicate.
Note:
Values are forced to help display.
Definition at line 22 of file gps.h.
Function Documentation
pos_t gps_closest (pos_t source, const void * targets, size_t nbTargets, map_content_t arrayType)
From a position, return the direction of the closest object in an array.
Parameters:
[in] source Source position.
[in] targets A vector to search in. Could be a vector of pos_t or of character_t.
[in] nbTargets Number of items in the vector "targets".
[in] arrayType Type of the content in "targets" (pos_t or character_t).
Returns:
pos_t Position of the closet item of "targets".
Definition at line 93 of file gps.c.
Referenced by _game_character_target().
const char* gps_compass_to_string (compass_t c)
Convert a compass into a string for display.
Parameters:
[in] c Direction to convert.
Returns:
const char* Constant string associated to the direction.
Note:
May be a unicode string.
Definition at line 86 of file gps.c.
Referenced by _display_string(), and _display_ui_player_body().
pos_t gps_compute_move (pos_t pos, compass_t move)
Compute the new positions after a move.
Parameters:
[in] pos The originale position.
[in] move The move to do.
Returns:
pos_t The new position.
Definition at line 131 of file gps.c.
Referenced by _character_make_move(), and _gave_solve_moves_conflicts().
void gps_direction (pos_t source, pos_t target, compass_t * pC, float * pD)
Return the direction and the distance between tow positions.
Parameters:
[in] source Source position.
[in] target Target position.
[out] pC The direction of the target from the source.
[out] pD Distance between the two positions.
Definition at line 60 of file gps.c.
Referenced by character_play(), game_init(), and gps_closest().
size_t gps_locator (const map_t * pMap, map_content_t object, pos_t ** pAPos)
Returns the number of objects of a given type in a map and their position.
Parameters:
[in] pMap The map to explore.
[in] object The type of object to search (player for instance).
[out] pAPos Array of positions found (must be free outside).
Returns:
size_t Number of objects found.
Definition at line 38 of file gps.c.
Referenced by game_init().