Operating System 2: Let's play in the dedalus!: src/display.h File Reference
src/display.h File Reference
Methods to display a dedalus.
#include <stdio.h>
#include "character.h"
#include "config.h"
#include "map.h"
Enumerations
enum ending_t {
EG_LOOSE, EG_NEXT_LEVEL_AND_ALIVE, EG_NEXT_LEVEL_BUT_DEAD, EG_WIN_AND_ALIVE,
EG_KILL_MINOTAUR_BUT_DEAD, EG_WIN_BUT_DEAD, EG_GM_WIN, EG_GM_LOOSE
}
Set of possible endings for players and game master.
Functions
void display_ui_gm (FILE *stream, const char *level, const map_t *pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, int delay, bool gameInfo, bool refresh)
Display the game master interface.
void display_ui_player (const char *level, const char *ia, const map_t *pMap, const character_t *pPlayer, int delay, int maxMoves, bool gameInfo, bool header, bool refresh)
Display a player interface.
void display_ending (FILE *stream, ending_t ending)
Display an ending message.
void display_fight_iteration (const map_t *pMap, const character_t *pC1, const character_t *pC2, size_t delay, size_t iteration)
Display on iteration of a fight.
void display_fight_clear (FILE *stream)
Clear the display of a finished fight.
void display_fatal_error (FILE *stream, const char *msg)
Display a fatal error.
void display_info (FILE *stream, const char *msg)
Display an information message.
void display_wait_user (FILE *stream, const char *preMsg, bool waitUser)
Wait a user interaction.
Detailed Description
Methods to display a dedalus.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-19
Copyright:
Copyright (c) 2019
Definition in file display.h.
Enumeration Type Documentation
enum ending_t
Set of possible endings for players and game master.
Enumerator:
EG_LOOSE
Player completely failed.
EG_NEXT_LEVEL_AND_ALIVE
The player found the exit.
EG_NEXT_LEVEL_BUT_DEAD
An other player found the exit.
EG_WIN_AND_ALIVE
Minotaur killed and player exits.
EG_KILL_MINOTAUR_BUT_DEAD
Minotaur dead but player dead.
EG_WIN_BUT_DEAD
Minotaur dead and some other players exits.
EG_GM_WIN
Game master won (all players are dead).
EG_GM_LOOSE
Game master failed (some players escaped).
Definition at line 25 of file display.h.
Function Documentation
void display_ending (FILE * stream, ending_t ending)
Display an ending message.
Parameters:
[in,out] stream Where it should be printed.
[in] ending The ending type to display.
Definition at line 870 of file display.c.
Referenced by game_start().
void display_fatal_error (FILE * stream, const char * msg)
Display a fatal error.
Parameters:
[in,out] stream Where the message should be printed.
[in] msg Message to print.
Note:
For debug only.
Definition at line 1003 of file display.c.
Referenced by _character_get_child_pid(), _game_death_caractere(), _game_exit_character(), _game_init_moves_prop(), _gave_solve_moves_conflicts(), character_init(), gps_closest(), and main().
void display_fight_clear (FILE * stream)
Clear the display of a finished fight.
Parameters:
[in,out] stream The stream to clean
Definition at line 991 of file display.c.
Referenced by _game_fight().
void display_fight_iteration (const map_t * pMap, const character_t * pC1, const character_t * pC2, size_t delay, size_t iteration)
Display on iteration of a fight.
Parameters:
[in] pMap The map to clear for the first iteration.
[in] pC1 First character for the fight.
[in] pC2 Second character for the fight.
[in] delay Delay between two frame of the introduction step.
[in] iteration Step of the fight.
Note:
The iteration is used of the animation. Basically it is a counter that should be incremented by one between each frame.
Definition at line 926 of file display.c.
Referenced by _game_fight().
void display_info (FILE * stream, const char * msg)
Display an information message.
Parameters:
[in,out] stream Where the message should be printed.
[in] msg The message to display.
Definition at line 1034 of file display.c.
Referenced by display_wait_user().
void display_ui_gm (FILE * stream, const char * level, const map_t * pMap, size_t nbPlayerAlive, size_t nbPlayerOnBoard, size_t nbMinotaurAlive, int delay, bool gameInfo, bool refresh)
Display the game master interface.
Parameters:
[in,out] stream Where it should be printed.
[in] level Name of the level.
[in] pMap Map to print.
[in] nbPlayerAlive Number of player still alive.
[in] nbPlayerOnBoard Number of player on board.
[in] nbMinotaurAlive Number of Minotaurs still alive.
[in] delay Delay between two frames (for information only).
[in] gameInfo Display more precise game informations.
[in] refresh If only the body of the ui should be refresh.
Definition at line 838 of file display.c.
Referenced by _game_play_refresh_ui(), and game_start().
void display_ui_player (const char * level, const char * ia, const map_t * pMap, const character_t * pPlayer, int delay, int maxMoves, bool gameInfo, bool header, bool refresh)
Display a player interface.
Parameters:
[in] level Level name.
[in] ia IA name.
[in] pMap Map to print.
[in] pPlayer Player considered for the point of view.
[in] delay Delay between two frames (for information only).
[in] maxMoves Max number of moved allowed.
[in] gameInfo Display more precise game informations.
[in] header If the header of the ui should be printed.
[in] refresh If the body of the ui should be refresh.
Note:
The output stream is defined inside the player.
Definition at line 854 of file display.c.
Referenced by _game_fight(), _game_play_refresh_ui(), and game_start().
void display_wait_user (FILE * stream, const char * preMsg, bool waitUser)
Wait a user interaction.
Parameters:
[in,out] stream The stream from where the interaction should happen.
[in] preMsg A one line message that could be printed to ask for interaction. It is removed after the interaction. NULL to display nothin.
[in] waitUser If this call really wait an interaction or just one second.
Definition at line 1044 of file display.c.
Referenced by _game_fight(), and main().