Operating System 2: Let's play in the dedalus!: src/ai.h File Reference
src/ai.h File Reference
AI definition and factory.
#include "ariadneString.h"
Data Structures
struct ai_t
Structure of a AI for a character.
Functions
ai_t ai_new (const char *name)
AI factory.
Detailed Description
AI definition and factory.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-28
Copyright:
Copyright (c) 2019
Definition in file ai.h.
Function Documentation
ai_t ai_new (const char * name)
AI factory.
Parameters:
[in] name Name of the AI to build.
Returns:
ai_t The build AI. If name unknow, return the default AI (A Shall not pass AI).
Definition at line 17 of file ai.c.
Referenced by character_is_dead(), character_is_out(), and main().