Operating System 2: Let's play in the dedalus!: src/ai/ai_random.c File Reference
src/ai/ai_random.c File Reference
Random Artificial Intelligence.
#include <stdbool.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include "ai_random.h"
Functions
compass_t _ai_random_policy (bool north, bool east, bool south, bool west, compass_t comp, float distance, string ariane)
Select the next move randomly between all possible moves.
const char * ai_random_get_name ()
Get the name of the random AI class.
ai_t ai_random_new ()
Create a new AI that will move randomly.
Detailed Description
Random Artificial Intelligence.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file ai_random.c.
Function Documentation
compass_t _ai_random_policy (bool north, bool east, bool south, bool west, compass_t comp, float distance, string ariane)
Select the next move randomly between all possible moves.
Parameters:
[in] north Is it possible to go north?
[in] east Is it possible to go east?
[in] south Is it possible to go south?
[in] west Is it possible to go west?
[in] comp Unused parameter.
[in] distance Unused parameter.
[in] ariane Unused parameter.
Returns:
compass_t The selected direction.
Definition at line 31 of file ai_random.c.
Referenced by ai_random_new().
const char* ai_random_get_name ()
Get the name of the random AI class.
Returns:
const char* The name of the AI.
Definition at line 82 of file ai_random.c.
Referenced by ai_new(), ai_random_new(), and main().
ai_t ai_random_new ()
Create a new AI that will move randomly.
Returns:
ai_t The new AI.
Definition at line 86 of file ai_random.c.
Referenced by ai_new().