Operating System 2: Let's play in the dedalus!: src/map.c File Reference
src/map.c File Reference
Map definition and management.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "config.h"
#include "display.h"
#include "map.h"
Functions
size_t _map_decr_unsigned (size_t i)
Return a decremented unsigned int.
size_t _map_incr_limit (size_t i, size_t limit)
Increment a number but not over a limit.
void map_delete (map_t *pMap)
Clear the content of the map.
bool map_reader (const char *filename, map_t *pMap, size_t mapMaxXSize)
Read a map from a file.
map_t * map_mask_init (const map_t *pMap)
Build an empty display mask from a map.
void map_mask_add (map_t *pMask, pos_t p)
Add a position to display in a map mask.
Detailed Description
Map definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-01-24
Copyright:
Copyright (c) 2019
Definition in file map.c.
Function Documentation
size_t _map_decr_unsigned (size_t i)
Return a decremented unsigned int.
Parameters:
[in] i Value to decrement.
Returns:
size_t i - 1 if i > 0 else 0.
Definition at line 43 of file map.c.
Referenced by map_mask_add().
size_t _map_incr_limit (size_t i, size_t limit)
Increment a number but not over a limit.
Parameters:
[in] i Value to increment.
[in] limit Limit for i.
Returns:
size_t i + 1 if i < limit else limit.
Definition at line 50 of file map.c.
Referenced by map_mask_add().
void map_delete (map_t * pMap)
Clear the content of the map.
Parameters:
[in,out] pMap Pointer to the map to clear.
Note:
The map itself is not free, only its content.
Definition at line 60 of file map.c.
Referenced by character_delete(), game_delete(), main(), and map_reader().
void map_mask_add (map_t * pMask, pos_t p)
Add a position to display in a map mask.
Parameters:
[in,out] pMask
[in] p Position to add in the mask (i.e. to display).
Note:
Add the given position and the neighborhood.
Definition at line 151 of file map.c.
Referenced by _character_make_move(), and game_init().
map_t* map_mask_init (const map_t * pMap)
Build an empty display mask from a map.
Parameters:
[in] pMap The map associated to the mask to create.
Returns:
map_t* An empty map mask (displays nothing).
Definition at line 138 of file map.c.
Referenced by game_init().
bool map_reader (const char * filename, map_t * pMap, size_t mapMaxXSize)
Read a map from a file.
Parameters:
[in] filename Path to the file that contains the map in a text format.
[out] pMap The loaded map if loading succeed, *NULL else).
[in] mapMaxXSize Maximum width of a board.
Returns:
true Loading succeed.
false Loading failed (wrong format or missing content)
Definition at line 75 of file map.c.
Referenced by main().