Operating System 2: Let's play in the dedalus!: src/character.h File Reference
src/character.h File Reference
Character definition and management.
#include <stdio.h>
#include <sys/types.h>
#include "ai.h"
#include "ariadneString.h"
#include "gps.h"
#include "map.h"
Data Structures
struct character_t
A character (player, Minotaur, dead, ...)
Enumerations
enum ending_char_t {
EC_NO_ENDING, EC_KILL_BY_M, EC_STARVE_MINOTAUR, EC_STARVE_NO_MINOTAUR,
EC_CHEAT_MINOTAUR, EC_CHEAT_NO_MINOTAUR, EC_ESCAPE, EC_WIN
}
Possible endings of a character.
Functions
character_t character_init (map_content_t type, pid_t id, bool dispInChild, const char *name, int health, ai_t ai)
Initialize a character.
compass_t character_propose_move (const character_t *pC, const map_t *pMap, bool *pCheated)
Ask a character the move she wants to play.
void character_play (character_t *pC, compass_t move, pos_t targetPos, map_t *pMap, int steps, int maxMoves, bool *pExited)
Play a move for a character.
void character_is_dead (map_t *pMap, character_t *pC)
Set a character as dead.
void character_is_out (map_t *pMap, character_t *pC)
A Charater exit the maze.
void character_delete (map_t *pMap, character_t *pC)
Clear a character structure.
Detailed Description
Character definition and management.
Author:
Chevelu Jonathan (jonathan.chevelu@irisa.fr)
Version:
0.1
Date:
2019-02-20
Copyright:
Copyright (c) 2019
Definition in file character.h.
Data Structure Documentation
struct character_t
A character (player, Minotaur, dead, ...)
Definition at line 41 of file character.h.
Data Fields
ai_t ai AI for the character.
string ariadne Ariadne string for the character.
ending_char_t ending What is the ending for the character.
double health Health of the character.
pid_t id Character identifier.
const char * name Name of the character.
map_t * pMask Mask of what is seen by the character.
pos_t pos Current position of the character.
FILE * stream The stream for the character display.
compass_t targetCompass Direction of the character target.
float targetDistance Distance to the character target.
map_content_t type Type of character (player, Minotaur, dead, ...).
map_content_t walkOn What is below the character (exit, dead, ...)
Enumeration Type Documentation
enum ending_char_t
Possible endings of a character.
Enumerator:
EC_NO_ENDING
It is not finish.
EC_KILL_BY_M
Character was killed by a Minotaur.
EC_STARVE_MINOTAUR
Character starve and is kill by a Minotaur.
EC_STARVE_NO_MINOTAUR
Character just starve.
EC_CHEAT_MINOTAUR
Character cheat and then killed by a Minotaur.
EC_CHEAT_NO_MINOTAUR
Character just cheat.
EC_ESCAPE
Character escaped.
EC_WIN
Character escaped after Minotaurs death.
Definition at line 26 of file character.h.
Function Documentation
void character_delete (map_t * pMap, character_t * pC)
Clear a character structure.
Parameters:
[in,out] pMap The map.
[in,out] pC The character to clear.
Definition at line 328 of file character.c.
Referenced by game_delete().
character_t character_init (map_content_t type, pid_t id, bool dispInChild, const char * name, int health, ai_t ai)
Initialize a character.
Parameters:
[in] type Type of character (player, Minotaur, ...).
[in] id The id of the character.
[in] dispInChild Display in the child of the PID process id.
[in] name Name of the character.
[in] health Initial health of the character.
[in] ai AI of the character.
Returns:
character_t An initialized character (ready to play).
Definition at line 208 of file character.c.
Referenced by game_init().
void character_is_dead (map_t * pMap, character_t * pC)
Set a character as dead.
Parameters:
[in,out] pMap The map.
[in,out] pC The dying character.
He will not move and change its type.
Definition at line 315 of file character.c.
Referenced by _game_death_caractere().
void character_is_out (map_t * pMap, character_t * pC)
A Charater exit the maze.
Parameters:
[in,out] pMap The map.
[in,out] pC The character that exit.
He will not move and his position will change.
Definition at line 322 of file character.c.
Referenced by _game_exit_character().
void character_play (character_t * pC, compass_t move, pos_t targetPos, map_t * pMap, int steps, int maxMoves, bool * pExited)
Play a move for a character.
Parameters:
[in,out] pC The considered character.
[in] move The desired move.
[in] targetPos Position of the character target.
[in,out] pMap The map.
[in] steps Number of steps from the begining.
[in] maxMoves Maximum number of steps before death.
[out] pExited Says if the charactere is on an exit after the move.
Definition at line 281 of file character.c.
Referenced by _game_play_character().
compass_t character_propose_move (const character_t * pC, const map_t * pMap, bool * pCheated)
Ask a character the move she wants to play.
Parameters:
[in] pC The considered character.
[in] pMap The map.
[out] pCheated Says if the AI tries to cheat?
Returns:
compass_t The desired move.
Definition at line 266 of file character.c.
Referenced by _game_get_moves_propositions().